name: sct
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py310h25320af_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.37.0=pyh8f84b5b_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1423503_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgomp=15.1.0=h767d61c_4
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.2=pyh8b19718_0
  - platformdirs=4.4.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py310h7c4b9e2_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.10.18=hd6af730_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.10=8_cp310
  - pyzmq=27.0.2=py310h4f33d48_2
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - six=1.17.0=pyhe01879c_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.13=noxft_hd72426e_102
  - tornado=6.5.2=py310h7c4b9e2_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=pyhd8ed1ab_1
  - zeromq=4.3.5=h3b0a872_7
  - zipp=3.23.0=pyhd8ed1ab_0
  - pip:
      - absl-py==2.3.1
      - acres==0.5.0
      - acvl-utils==0.2.5
      - annotated-types==0.7.0
      - argparse==1.4.0
      - astor==0.8.1
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - bids-validator==1.14.7.post0
      - bidsschematools==1.0.14
      - blessed==1.21.0
      - blosc2==3.7.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - ci-info==0.3.0
      - click==8.2.1
      - coloredlogs==15.0.1
      - connected-components-3d==3.24.0
      - contourpy==1.3.2
      - coverage==7.10.6
      - csv-diff==1.2
      - cycler==0.12.1
      - cython==3.1.3
      - deepdiff==8.6.0
      - deprecated==1.2.18
      - dicom2nifti==2.6.2
      - dictdiffer==0.9.0
      - dipy==1.8.0
      - docopt==0.6.2
      - dynamic-network-architectures==0.3.1
      - editor==1.6.6
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - etelemetry==0.3.1
      - fft-conv-pytorch==1.2.0
      - filelock==3.19.1
      - flatbuffers==25.2.10
      - fonttools==4.59.2
      - formulaic==0.3.4
      - fsspec==2025.7.0
      - future==1.0.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.74.0
      - gryds==0.0.9
      - h5py==3.14.0
      - humanfriendly==10.0
      - humanize==4.13.0
      - idna==3.10
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - inquirer==3.4.1
      - interface-meta==1.3.0
      - isodate==0.7.2
      - ivadomed==2.9.10
      - jinja2==3.1.6
      - joblib==1.5.2
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linecache2==1.0.0
      - loguru==0.7.3
      - looseversion==1.3.0
      - lxml==6.0.1
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdurl==0.1.2
      - monai==1.4.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - ndindex==1.10.0
      - networkx==3.4.2
      - neurite==0.2
      - nibabel==5.3.2
      - nilearn==0.10.4
      - nipype==1.10.0
      - nnunetv2==2.5.2
      - num2words==0.5.14
      - numexpr==2.11.0
      - numpy==1.26.4
      - onnx==1.16.1
      - onnxruntime==1.21.1
      - openpyxl==3.1.5
      - orderly-set==5.5.0
      - pandas==1.5.3
      - pillow==11.3.0
      - pluggy==1.6.0
      - portalocker==3.2.0
      - protobuf==6.32.0
      - prov==2.1.1
      - puremagic==1.30
      - py-cpuinfo==9.0.0
      - pybids==0.15.5
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydicom==3.0.1
      - pydot==4.0.1
      - pyparsing==3.2.3
      - pypdf2==3.0.1
      - pyqt5==5.15.11
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.17.0
      - pystrum==0.4
      - pytest==8.4.1
      - pytest-console-scripts==1.4.1
      - pytest-cov==6.2.1
      - python-gdcm==3.0.26
      - python-graphviz==0.21
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdflib==7.1.4
      - readchar==4.2.1
      - requests==2.32.5
      - requirements-parser==0.13.0
      - rich==14.1.0
      - runs==1.2.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.1
      - scipy==1.15.3
      - seaborn==0.13.2
      - sentry-sdk==2.35.2
      - setuptools-scm==9.2.0
      - shellingham==1.5.4
      - simpleitk==2.5.2
      - simplejson==3.20.1
      - smmap==5.0.2
      - spinalcordtoolbox==7.1
      - sqlalchemy==1.3.24
      - strenum==0.4.15
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tomli==2.2.1
      - torch==2.2.2+cpu
      - torchio==0.20.21
      - torchvision==0.17.2+cpu
      - totalspineseg==20250709
      - tqdm==4.67.1
      - traceback2==1.4.0
      - traits==7.0.2
      - transforms3d==0.4.2
      - trx-python==0.3
      - typer==0.17.3
      - typing-inspection==0.4.1
      - unittest2==1.1.0
      - urllib3==2.5.0
      - voxelmorph==0.2
      - wandb==0.21.3
      - werkzeug==3.1.3
      - wquantiles==0.6
      - wrapt==1.17.3
      - xlrd==2.0.2
      - xlsxwriter==3.2.5
      - xlwt==1.3.0
      - xmod==1.8.1
      - yacs==0.1.8
